version: '3.7'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - URL_ECON_API=${URL_ECON_API}
    ports:
    - "80:80"
    restart: always
  
  
